In [11]:
%cd ..
import pandas as pd 
from src.database import engine


query="""
    SELECT *
    FROM patients
"""

patients = pd.read_sql(query, engine)
patients.head(10)

/Users/frank/Data Science Projects

/Users/frank/DataLearning/dsenve/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

   subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0    10014729      F          21         2125       2011 - 2013
1    10003400      F          72         2134       2011 - 2013  2137-09-02
2    10002428      F          80         2155       2011 - 2013
3    10032725      F          38         2143       2011 - 2013  2143-03-30
4    10027445      F          48         2142       2011 - 2013  2146-02-09
5    10037928      F          78         2175       2011 - 2013
6    10001725      F          46         2110       2011 - 2013
7    10040025      F          64         2143       2011 - 2013  2148-02-07
8    10008454      F          26         2110       2011 - 2013
9    10020640      F          91         2153       2011 - 2013  2154-02-04

In [12]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subject_id         100 non-null    int64
 1   gender             100 non-null    object
 2   anchor_age         100 non-null    int64
 3   anchor_year        100 non-null    int64
 4   anchor_year_group  100 non-null    object
 5   dod                100 non-null    object
dtypes: int64(3), object(3)
memory usage: 4.8+ KB

- 100 entries
- 3 objects and 3 integer data types
- 4.8 KB of memory usage
- Column names: subject_id, gender, anchor_age, anchor_year, anchor_yaer_group, dod

In [16]:
patients.describe()

         subject_id  anchor_age  anchor_year
count  1.000000e+02   100.00000   100.000000
mean   1.001878e+07    61.75000  2148.680000
std    1.115115e+04    16.16979    25.629008
min    1.000003e+07    21.00000  2110.000000
25%    1.000889e+07    51.75000  2129.000000
50%    1.001909e+07    63.00000  2145.500000
75%    1.002550e+07    72.00000  2172.500000
max    1.004002e+07    91.00000  2201.000000

- The mean, std, min and max values are given above

In [17]:
patients.isnull().sum()

subject_id           0
gender               0
anchor_age           0
anchor_year          0
anchor_year_group    0
dod                  0
dtype: int64

- Zero null values exist within the columns indicated

In [20]:
query="""
    SELECT *
    FROM admissions
"""

admissions = pd.read_sql(query, engine)
admissions.head()

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10004235,24181354,2196-02-24 14:38:00,2196-03-04 14:02:00,,URGENT,P03YMR,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicaid,ENGLISH,SINGLE,BLACK/CAPE VERDEAN,2196-02-24 12:15:00,2196-02-24 17:07:00,0
1,10009628,25926192,2153-09-17 17:08:00,2153-09-25 13:20:00,,URGENT,P41R5N,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicaid,?,MARRIED,HISPANIC/LATINO - PUERTO RICAN,,,0
2,10018081,23983182,2134-08-18 02:02:00,2134-08-23 19:35:00,,URGENT,P233F6,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicare,ENGLISH,MARRIED,WHITE,2134-08-17 16:24:00,2134-08-18 03:15:00,0
3,10006053,22942076,2111-11-13 23:39:00,2111-11-15 17:20:00,2111-11-15 17:20:00,URGENT,P38TI6,TRANSFER FROM HOSPITAL,DIED,Medicaid,ENGLISH,,UNKNOWN,,,1
4,10031404,21606243,2113-08-04 18:46:00,2113-08-06 20:57:00,,URGENT,P07HDB,TRANSFER FROM HOSPITAL,HOME,Other,ENGLISH,WIDOWED,WHITE,,,0

In [21]:
admissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   subject_id            275 non-null    int64
 1   hadm_id               275 non-null    int64
 2   admittime             275 non-null    object
 3   dischtime             275 non-null    object
 4   deathtime             275 non-null    object
 5   admission_type        275 non-null    object
 6   admit_provider_id     275 non-null    object
 7   admission_location    275 non-null    object
 8   discharge_location    275 non-null    object
 9   insurance             275 non-null    object
 10  language              275 non-null    object
 11  marital_status        275 non-null    object
 12  race                  275 non-null    object
 13  edregtime             275 non-null    object
 14  edouttime             275 non-null    object
 15  hospital_expire_flag  275 non-null    int64
dtypes: int64(3), object(13)
memory usage: 34.5+ KB

In [22]:
admissions.describe()

         subject_id       hadm_id  hospital_expire_flag
count  2.750000e+02  2.750000e+02            275.000000
mean   1.001890e+07  2.513055e+07              0.054545
std    1.212777e+04  2.907533e+06              0.227505
min    1.000003e+07  2.004459e+07              0.000000
25%    1.000787e+07  2.258313e+07              0.000000
50%    1.001808e+07  2.517230e+07              0.000000
75%    1.002626e+07  2.767155e+07              0.000000
max    1.004002e+07  2.997458e+07              1.000000

In [23]:
admissions.isnull().sum()

subject_id              0
hadm_id                 0
admittime               0
dischtime               0
deathtime               0
admission_type          0
admit_provider_id       0
admission_location      0
discharge_location      0
insurance               0
language                0
marital_status          0
race                    0
edregtime               0
edouttime               0
hospital_expire_flag    0
dtype: int64

In [61]:
df = patients.merge(
    admissions, 
    on = "subject_id",
    how = "inner"
)

df.head()
# display(df.style.hide())

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod,hadm_id,admittime,dischtime,deathtime,...,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10014729,F,21,2125,2011 - 2013,,23300884,2125-03-19 16:58:00,2125-03-28 13:37:00,,...,P76K54,EMERGENCY ROOM,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE - OTHER EUROPEAN,2125-03-19 12:36:00,2125-03-19 18:45:00,0
1,10014729,F,21,2125,2011 - 2013,,28889419,2125-02-27 07:15:00,2125-03-06 14:25:00,,...,P17BJ5,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE - OTHER EUROPEAN,,,0
2,10003400,F,72,2134,2011 - 2013,2137-09-02,23559586,2137-08-04 00:07:00,2137-09-02 17:05:00,2137-09-02 17:05:00,...,P99U21,TRANSFER FROM HOSPITAL,DIED,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,,,1
3,10003400,F,72,2134,2011 - 2013,2137-09-02,20214994,2137-02-24 10:00:00,2137-03-19 15:45:00,,...,P60ZCO,TRANSFER FROM SKILLED NURSING FACILITY,CHRONIC/LONG TERM ACUTE CARE,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,,,0
4,10003400,F,72,2134,2011 - 2013,2137-09-02,27296885,2136-12-31 21:40:00,2137-01-03 17:05:00,,...,P14622,EMERGENCY ROOM,SKILLED NURSING FACILITY,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,2136-12-31 13:41:00,2137-01-01 00:35:00,0

In [62]:
df.drop(columns=["gender"])

,subject_id,anchor_age,anchor_year,anchor_year_group,dod,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10014729,21,2125,2011 - 2013,,23300884,2125-03-19 16:58:00,2125-03-28 13:37:00,,EW EMER.,P76K54,EMERGENCY ROOM,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE - OTHER EUROPEAN,2125-03-19 12:36:00,2125-03-19 18:45:00,0
1,10014729,21,2125,2011 - 2013,,28889419,2125-02-27 07:15:00,2125-03-06 14:25:00,,SURGICAL SAME DAY ADMISSION,P17BJ5,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE - OTHER EUROPEAN,,,0
2,10003400,72,2134,2011 - 2013,2137-09-02,23559586,2137-08-04 00:07:00,2137-09-02 17:05:00,2137-09-02 17:05:00,URGENT,P99U21,TRANSFER FROM HOSPITAL,DIED,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,,,1
3,10003400,72,2134,2011 - 2013,2137-09-02,20214994,2137-02-24 10:00:00,2137-03-19 15:45:00,,URGENT,P60ZCO,TRANSFER FROM SKILLED NURSING FACILITY,CHRONIC/LONG TERM ACUTE CARE,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,,,0
4,10003400,72,2134,2011 - 2013,2137-09-02,27296885,2136-12-31 21:40:00,2137-01-03 17:05:00,,EW EMER.,P14622,EMERGENCY ROOM,SKILLED NURSING FACILITY,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,2136-12-31 13:41:00,2137-01-01 00:35:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,10021118,62,2161,2014 - 2016,,24490144,2161-11-15 20:10:00,2161-11-23 16:00:00,,URGENT,P96FGV,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Other,ENGLISH,MARRIED,WHITE,,,0
271,10018501,83,2141,2014 - 2016,,28479513,2141-07-30 22:34:00,2141-08-05 18:06:00,,EW EMER.,P99698,EMERGENCY ROOM,SKILLED NURSING FACILITY,Medicare,ENGLISH,,WHITE,2141-07-30 18:53:00,2141-07-31 00:01:00,0
272,10007058,48,2167,2014 - 2016,,22954658,2167-11-07 19:05:00,2167-11-11 14:23:00,,EW EMER.,P76K54,EMERGENCY ROOM,HOME,Other,ENGLISH,MARRIED,WHITE,2167-11-07 17:57:00,2167-11-07 20:22:00,0
273,10038992,70,2185,2014 - 2016,,22797747,2185-11-02 18:26:00,2185-11-08 16:22:00,,URGENT,P534S8,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicare,ENGLISH,MARRIED,UNKNOWN,,,0
274,10038992,70,2185,2014 - 2016,,24745425,2187-07-29 01:05:00,2187-08-03 17:02:00,,SURGICAL SAME DAY ADMISSION,P41R5N,PHYSICIAN REFERRAL,SKILLED NURSING FACILITY,Medicare,ENGLISH,MARRIED,WHITE,,,0

In [63]:
df.shape

(275, 21)

In [ ]:
df.isnull().sum()

subject_id              0
gender                  0
anchor_age              0
anchor_year             0
anchor_year_group       0
dod                     0
hadm_id                 0
admittime               0
dischtime               0
deathtime               0
admission_type          0
admit_provider_id       0
admission_location      0
discharge_location      0
insurance               0
language                0
marital_status          0
race                    0
edregtime               0
edouttime               0
hospital_expire_flag    0
dtype: int64

In [68]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
270    False
271    False
272    False
273    False
274    False
Length: 275, dtype: bool

In [69]:
df.duplicated().sum()

np.int64(0)

In [75]:
duplicate_rows = df[df.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [subject_id, gender, anchor_age, anchor_year, anchor_year_group, dod, hadm_id, admittime, dischtime, deathtime, admission_type, admit_provider_id, admission_location, discharge_location, insurance, language, marital_status, race, edregtime, edouttime, hospital_expire_flag]
Index: []

[0 rows x 21 columns]